### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by simingbayer** [sjoerdvansteenkiste/Neural-EM#4]
Dear Sjoerd,

Currently, I am trying to work with your NEM framework. 
However, I could not run it successfully.
The error I get is the following:

Traceback (most recent calls WITHOUT Sacred internals):
  File "nem.py", line 336, in run
    train_op, train_graph, valid_graph, debug_graph = build_graphs(train_inputs.output, valid_inputs.output)
  File "nem.py", line 152, in build_graphs
    train_graph = build_graph(train_inputs['features'], train_inputs['groups'])
  File "nem.py", line 119, in build_graph
    static_nem_iterations(features_corrupted, features, dataset['binary'])
  File "D:\Unsupervised Learning\Neural-EM\nem_model.py", line 305, in static_nem_iterations
    nem_cell = NEMCell(inner_cell, input_shape=(W, H, C), distribution=pixel_dist)
  File "D:\Unsupervised Learning\Neural-EM\nem_model.py", line 50, in __init__
    self.input_shape = input_shape
AttributeError: can't set attribute

Do you have any experience about it?
Thank you for your help!

Best,
Siming

**Comment by sjoerdvansteenkiste** [comment]
Hi Siming,

This error occurs because you are using a newer tensorflow version than the code was written for. Later versions of tensorflow given RNNCell the property input_shape, which here we use as an internal variable that results in the conflict. 

You can either rename self.input_shape (as done in the code of our follow-up work that has been tested with tf 1.9: see [here](https://github.com/sjoerdvansteenkiste/Relational-NEM/commit/d694d6957f2c14ed3246f8692fe30d92f281b68d)) or downgrading your tensorflow version to meet the requirements. 

Let me know if this works!

Cheers,

Sjoerd

**Comment by simingbayer** [comment]
Great! Thank you very much. I just create a new evironment with lower tensorflow version. It works :-)

best,
Siming
